# Generated by Django 4.1.7 on 2023-03-14 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('contract_type', models.CharField(choices=[('COE', 'Umowa o pracę'), ('CW', 'Umowa o dzieło'), ('MC', 'Umowa zlecenie'), ('B2B', 'Umowa B2B'), ('RC', 'Umowa zastępstwa'), ('AA', 'Umowa agencyjna'), ('TEC', 'Umowa o pracę tymczasową'), ('IC', 'Umowa stażowa')], max_length=50)),
                ('working_type', models.CharField(choices=[('FT', 'Pełny etat'), ('PT', 'Praca na niepełny etat'), ('SJ', 'Praca sezonowa')], max_length=50)),
                ('month_salary', models.IntegerField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_ads.industry')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_ads.position')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='\\job_application_resumes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker')),
            ],
        ),
    ]
