# Generated by Django 4.1.7 on 2023-03-19 00:44

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', accounts.models.CompanyManager()),
            ],
        ),
    ]
